export const btnSX = {
  width: 'fit-content',
  background: 'var(--orange)',
  border: '1px solid var(--orange)',
  borderRadius: '6px',
  boxShadow: 'rgba(0, 0, 0, 0.1) 1px 2px 4px',
  boxSizing: 'border-box',
  color: 'var(--white)',
  cursor: 'pointer',
  display: 'inline-block',
  fontFamily: 'nunito, roboto, proxima-nova, "proxima nova", sans-serif',
  lineHeight: '16px',
  minHeight: '40px',
  outline: '0',
  padding: '12px 14px',
  textAlign: 'center',
  textRendering: 'geometricprecision',
  textTransform: 'none',
  userSelect: 'none',
  WebkitUserSelect: 'none',
  touchAction: 'manipulation',
  verticalAlign: 'middle',
  '&:hover, &:active': {
    backgroundColor: 'initial',
    backgroundPosition: '0 0',
    color: 'var(--orange)',
  },
  '&:active': {
    opacity: 0.5,
  },
  '&:disabled': {
    backgroundColor: 'var(--gray)',
    border: '1px solid var(--gray)',
    color: 'var(--light-gray)',
    cursor: 'not-allowed',
    opacity: 0.5,
  },
};
