paths:
  /config:
    get:
      security:
        - Keycloak:
            - openid
            - email
      tags:
        - Server
      summary: Retrieve configuration variables
      description: Returns an object containing configuration variables for the frontend.
      operationId: getConfiguration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ENVIRONMENT:
                    type: string
                example:
                  ENVIRONMENT: production
