# Directory: .
# Create me with the 'npm run init' command.

# Disable/enable me with the 'npm run toggle-dev' command.
services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend/src:/app/src
